### ISSUE TITLE
Data quality issue: `CT_US_COVID_TESTS`

### ISSUE THREAD

**Issue by joelash** [starschema/COVID-19-data#351]
**Describe the bug**
In `CT_US_COVID_TESTS`, no new data since March 7, 2021

**Describe the expected result**
`CT_US_COVID_TESTS` should have recent data

**Verification**
`DATE` should be recent.
```sql
SELECT *
FROM COVID19_STAR.PUBLIC.CT_US_COVID_TESTS
ORDER BY DATE desc;
```

**Comment by tfoldi** [comment]
hi Joelash, the issue was fixed in the meantime - it should be replicated within 60 minutes to all snowflake region.

**Comment by joelash** [comment]
Thanks @tfoldi, I still don't see this correct in our database. Is there anything I need to do on my side?

**Comment by chrisvoncsefalvay** [comment]
Hi @joelash – the table you're looking at is the Covid Tracking Project's data set. As noted [here](https://medium.com/starschema-blog/the-covid-tracking-project-is-shutting-down-in-a-week-what-next-5c791cebe451), this table is no longer updated because the source data set is no longer updated (see also [this](https://covidtracking.com/analysis-updates/covid-tracking-project-end-march-7)). You may find the data points you need in other tables, however. Please feel free to let me know if there's anything else I can assist you with!

**Comment by joelash** [comment]
Thanks @chrisvoncsefalvay, I sort of assumed that but couldn't find info about it.
